# Generated by Django 3.2.7 on 2021-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='contact',
        ),
        migrations.AddField(
            model_name='policy',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contact_fax',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contact_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contact_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='contact_unit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
