# Generated by Django 3.2.7 on 2021-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_change_allow_null'),
        ('policy', '0002_move_contact_to_policy_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tag.Tag'),
        ),
    ]
