# Generated by Django 3.2.7 on 2022-01-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_change_amount_quota_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='website_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
