# Generated by Django 3.2.7 on 2021-10-22 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_contact_creation', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_contact_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demonstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('location_url', models.URLField(null=True)),
                ('video_url', models.URLField(null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(default='5g', max_length=10)),
                ('preview', models.ImageField(null=True, upload_to='demonstrations/images')),
                ('by_mrt', models.TextField(blank=True, default='', null=True)),
                ('by_bus', models.TextField(blank=True, default='', null=True)),
                ('by_drive', models.TextField(blank=True, default='', null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demonstration.contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_demonstration_creation', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_demonstration_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_link_creation', to=settings.AUTH_USER_MODEL)),
                ('demonstration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='demonstration.demonstration')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_link_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('file', models.ImageField(null=True, upload_to='demonstrations/images')),
                ('size', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_image_creation', to=settings.AUTH_USER_MODEL)),
                ('demonstration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='demonstration.demonstration')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_image_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('file', models.ImageField(null=True, upload_to='demonstrations/files')),
                ('size', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_file_creation', to=settings.AUTH_USER_MODEL)),
                ('demonstration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='demonstration.demonstration')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demonstration_file_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
