# Generated by Django 3.2.7 on 2021-10-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demonstration',
            old_name='by_bus',
            new_name='video_iframe',
        ),
        migrations.RemoveField(
            model_name='demonstration',
            name='by_drive',
        ),
        migrations.RemoveField(
            model_name='demonstration',
            name='by_mrt',
        ),
        migrations.RemoveField(
            model_name='demonstration',
            name='video_url',
        ),
        migrations.AddField(
            model_name='demonstration',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
