# Generated by Django 3.2.7 on 2021-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0002_remove_traffic_add_address_video_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='preview',
            field=models.URLField(null=True),
        ),
    ]
