# Generated by Django 3.2.7 on 2021-10-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0003_change_preview_to_urlfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updater',
        ),
    ]
