# Generated by Django 3.2.7 on 2021-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0006_change_preview_to_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='location_url',
            field=models.TextField(null=True),
        ),
    ]
