# Generated by Django 3.2.7 on 2021-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0008_add_by_mrt_by_bus_back_change_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demonstration',
            old_name='link',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='demonstration',
            name='website_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='demonstrations/files'),
        ),
    ]
