# Generated by Django 3.2.7 on 2021-11-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0009_rename_url_to_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
