# Generated by Django 3.2.7 on 2021-11-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0010_increase_file_type_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
