# Generated by Django 3.2.7 on 2021-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonstration', '0011_change_description_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstration',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
