# Generated by Django 3.2.7 on 2021-09-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
