# Generated by Django 3.2.7 on 2021-10-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_add_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
