# Generated by Django 3.2.7 on 2021-10-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='creator',
        ),
    ]
