# Generated by Django 3.2.7 on 2021-10-05 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_add_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_news_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
