# Generated by Django 3.2.7 on 2021-10-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_change_default_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
