# Generated by Django 3.2.7 on 2021-10-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_change_allow_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hot_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
