# Generated by Django 3.2.7 on 2023-11-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_change_news_description_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
