name: Deploy to Cloud Run
on:
  push:
    branches:
      - master

env:
  PROJECT_ID: cht-fiveg
  SERVICE_NAME: backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.CHT_FIVEG_GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Set kaniko cache
        run: gcloud config set builds/use_kaniko True
      - name: Build image
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$SERVICE_NAME:latest"
  build:
    name: Build
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.CHT_FIVEG_GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Deploy to Cloud Run
        env:
          GS_BUCKET_NAME: backend-django
          REGION: asia-east1
          DATABASE_INSTANCE: cht-fiveg-sql
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --region asia-east1 \
            --image "asia-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$SERVICE_NAME:latest" \
            --platform "managed" \
            --quiet \
            --add-cloudsql-instances ${{ env.PROJECT_ID }}:${{ env.REGION }}:${{ env.DATABASE_INSTANCE }} \
            --set-env-vars PRODUCTION=true,DB_USER="${{ secrets.DB_USER }}",DB_PASS="${{ secrets.DB_PASS }}",SQL_HOST="${{ secrets.SQL_HOST }}",DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}",API_HOST="${{ secrets.API_HOST }}"