name: Deploy to Cloud Run
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: cht-fiveg
          service_account_key: ${{ secrets.CHT_FIVEG_GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy backend
          --source .
          --platform managed
          --region asia-east1
          --add-cloudsql-instances cht-fiveg:asia-east1:cht-fiveg-sql
          --allow-unauthenticated
          --set-env-vars DB_USER=${{ secrets.DB_USER }},DB_PASS=${{ secrets.DB_PASS }},SQL_HOST=${{ secrets.SQL_HOST }},DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }},DEBUG=${{ secrets.DEBUG }},API_HOST=${{ secrets.API_HOST }}