# Generated by Django 3.2.7 on 2021-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_add_size_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
