# Generated by Django 3.2.7 on 2021-09-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_debug_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='length',
            new_name='banner_length',
        ),
    ]
