# Generated by Django 3.2.7 on 2021-10-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='tag',
            new_name='tags',
        ),
    ]
