# Generated by Django 3.2.7 on 2021-10-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_add_editorbasemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
