# Generated by Django 3.2.7 on 2021-10-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_change_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
