# Generated by Django 3.2.7 on 2021-11-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_privacy_and_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
