# Generated by Django 3.2.7 on 2021-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_extend_description_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
