# Generated by Django 3.2.7 on 2023-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_change_partner_phone_email_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='loop_time',
            field=models.IntegerField(default=6),
        ),
    ]
